name: Build and Release

on: workflow_dispatch

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.gitversion.outputs.FullSemVer }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.2.1
        with:
          versionSpec: '6.3.x'

      - name: Run GitVersion
        id: gitversion
        uses: GitTools/actions/gitversion/execute@v3.2.1

  build:
    runs-on: windows-latest
    needs: version
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish project (minimal)
        run: dotnet publish ./PhaethonsNomikon/PhaethonsNomikon.csproj -c Release /p:Version=${{ needs.version.outputs.version }} -o output

      - name: Create ZIP archive (minimal)
        run: Compress-Archive -Path output\* -DestinationPath PhaethonsNomikon-${{ needs.version.outputs.version }}.zip

      - name: Publish project (self-contained)
        run: dotnet publish ./PhaethonsNomikon/PhaethonsNomikon.csproj -c Release /p:Version=${{ needs.version.outputs.version }} -o output-sc

      - name: Create ZIP archive (self-contained)
        run: Compress-Archive -Path output-sc\* -DestinationPath PhaethonsNomikon-${{ needs.version.outputs.version }}-self-contained.zip

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 
          - PhaethonsNomikon-${{ needs.version.outputs.version }}.zip
          - PhaethonsNomikon-${{ needs.version.outputs.version }}-self-contained.zip
          tag: v${{ needs.version.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
